server:
  port: 3001

sping:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user?useSSL=false
    username: sportuser
    password: 1234567890
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create  #//!!!!
    show-sql: true


