server:
  port: ${PORT}

eureka:
  instance:
    hostname: becomethebest.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
    non-secure-port-enabled: true
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: https://eureka.herokuapp.com/eureka/
      non-secure-port: 80
      secure-port: 443

spring:
  application:
    name: user
  datasource:
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${USER}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


