server:
  port: ${PORT:8901}

eureka:
  instance:
    hostname: user.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
    non-secure-port-enabled: true
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: http://eureka.herokuapp.com/eureka/
      non-secure-port: 80
      secure-port: 443

spring:
  application:
    name: event
  datasource:
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${USER}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true