server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:${server.port}/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME:localhost}