server:
  port: 3001

spring:
  application:
    name: eureka
  zipkin:
    base-url: http://localhost:9411

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost