server:
  port: ${PORT:8761}

spring:
  profiles: peer
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:${server.port}/eureka/}
  instance:
    hostname: becomethebest.herokuapp.com