server:
  port: ${PORT}

spring:
  profiles: peer
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://becomethebest.herokuapp.com/eureka/
  instance:
    non-secure-port: 80
    hostname: becomethebest.herokuapp.com