server:
  port: ${PORT:8761}

spring:
  profiles: peer
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://becomethebest.herokuapp.com:8761/eureka/
  instance:
    hostname: becomethebest.herokuapp.com