server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: becomethebest.herokuapp.com
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: http://eureka.herokuapp.com/eureka/

ribbon:
  eureka:
    enabled: true

spring:
  application:
    name: gate

zuul:
  routes:
    users:
      path: /users/**
      serviceId: user
    events:
      path: /events/**
      serviceId: event