spring:
  application:
    name: gate

server:
  port: ${PORT}

eureka:
  instance:
    hostname: becomethebest.herokuapp.com
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://eureka.herokuapp.com/eureka/

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - routes
          - info
          - health

zuul:
  routes:
    users:
      path: /users/**
      serviceId: user
    events:
      path: /events/**
      serviceId: event